import Head from 'next/head'
import Image from 'next/image'
import { Inter, Poppins } from 'next/font/google'
import { HomePage, Apparel, StoreCategories, ShopElegant, CartButton, AboutLink, PhotoCollage, OverlaySection } from '../exports'
import { favicon } from '@/images'

const inter = Inter({ subsets: ['latin'] })
const poppins = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>CartO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full min-h-screen overflow-hidden'>
        <HomePage />
        <CartButton />
        <AboutLink inter={inter} poppins={poppins}/>
        <Apparel />
        <PhotoCollage inter={inter} poppins={poppins}/>
        <OverlaySection inter={inter} poppins={poppins} />
        <StoreCategories />
        <ShopElegant />
      </main>
    </>
  )
}
